# https://github.com/seanmaxwell/godot-example-auto-deploy/blob/main/.github/workflows/godot-ci.yml

name: Publish to itch.io
on:
  push:
    tags:
      - "v*"

env:
  ITCHIO_USERNAME: thewarlock
  GAME_NAME: yggdrasil-prototype-1
  PROJECT_PATH: "./src/"
  GODOT_VERSION: 4.5-stable

jobs:
  export-game:
    name: Export game
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Export
        id: export
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/${{env.GODOT_VERSION}}/Godot_v${{env.GODOT_VERSION}}_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/${{env.GODOT_VERSION}}/Godot_v${{env.GODOT_VERSION}}_export_templates.tpz
          relative_project_path: ${{ env.PROJECT_PATH}}
          use_preset_export_path: true
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.GAME_NAME }}.${{ github.ref_name }}.windows
          path: ${{ steps.export.outputs.build_directory }}/Windows Desktop
      - name: Upload MacOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.GAME_NAME }}.${{ github.ref_name }}.mac
          path: ${{ steps.export.outputs.build_directory }}/macOS
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.GAME_NAME }}.${{ github.ref_name }}.linux
          path: ${{ steps.export.outputs.build_directory }}/LinuxX11
      - name: Upload Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.GAME_NAME }}.${{ github.ref_name }}.web
          path: ${{ steps.export.outputs.build_directory }}/Web

  itch-io-upload:
    name: Upload to Itch.io
    needs: [export-game]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [web] # Other options: windows, mac, linux
    steps:
      - name: Download Artifact (${{ matrix.platform }})
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.GAME_NAME }}.${{ github.ref_name }}.${{ matrix.platform }}
      - name: Butler Upload
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: ${{ matrix.platform }}
          ITCH_GAME: ${{ env.GAME_NAME }}
          ITCH_USER: ${{ env.ITCHIO_USERNAME }}
          PACKAGE: .
          VERSION: ${{ github.ref_name }}
